[package]
name = "dust"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
dust_vdb = { path = "crates/vdb" }
dust_vox = { path = "crates/vox" }
dust_pbr = { path = "crates/pbr" }
dust_app = { path = "crates/app" }
pumicite = { path = "../pumicite" }
bevy_pumicite = { path = "../pumicite/crates/bevy" }

[dependencies]
dust_vox.workspace = true
dust_pbr.workspace = true
dust_app.workspace = true
bevy.workspace = true
pumicite.workspace = true
bevy_pumicite.workspace = true

[build-dependencies]
spirv-builder = { path = "../rust-gpu/crates/spirv-builder" }

[workspace.dependencies.bevy]
version = "0.18.1"
default-features = false
features = [
  "std",
  "async_executor",
  "bevy_winit",
  "bevy_log",
  "bevy_window",
  "bevy_camera",
  "bevy_asset",
  "bevy_scene",
  "free_camera",
  "debug",
  "reflect_auto_register",
  "multi_threaded",
]

[patch.crates-io]
ash = { git = "https://github.com/0xbeefd1ed/ash.git", branch = "meta" }

[patch."https://github.com/ash-rs/ash.git"]
ash = { git = "https://github.com/0xbeefd1ed/ash.git", branch = "meta" }

[patch."https://github.com/ash-rs/ash"]
ash = { git = "https://github.com/0xbeefd1ed/ash.git", branch = "meta" }

[profile.release]
debug = true

[profile.dev.package.dust_vdb]
opt-level = 3
